{% set version = '1.0.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-plot3drgl
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/plot3Drgl_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/plot3Drgl/plot3Drgl_{{ version }}.tar.gz
  sha256: 466d428d25c066c9c96d892f24da930513d42b1bdf76d3b53628c3ba13c3e48a

build:
  merge_build_host: True  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-plot3d
    - r-rgl
  run:
    - r-base
    - r-plot3d
    - r-rgl

test:
  commands:
    - $R -e "library('plot3Drgl')"           # [not win]
    - "\"%R%\" -e \"library('plot3Drgl')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=plot3Drgl
  license: GPL (>= 3.0)
  summary: The 'rgl' implementation of plot3D functions.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: plot3Drgl
# Version: 1.0.1
# Title: Plotting Multi-Dimensional Data - Using 'rgl'
# Author: Karline Soetaert <karline.soetaert@nioz.nl>
# Maintainer: Karline Soetaert <karline.soetaert@nioz.nl>
# Depends: rgl, plot3D, R (>= 3.2.3)
# Imports: grDevices
# Description: The 'rgl' implementation of plot3D functions.
# License: GPL (>= 3.0)
# LazyData: yes
# Packaged: 2016-01-17 12:45:42 UTC; rforge
# Repository: CRAN
# Repository/R-Forge/Project: plot3d
# Repository/R-Forge/Revision: 114
# Repository/R-Forge/DateTimeStamp: 2016-01-17 12:23:06
# Date/Publication: 2016-01-18 13:17:38
# NeedsCompilation: no
