travis:
  secure:
    BINSTAR_TOKEN: O8ZXOA0p/9ZyfsxeyH3RsLAGuxJlIov6F4UbmDXbIOk1zvLLKTFbP6ZZ7HD/oCTX7J6qkHJDOddIIrQPI0gSaG6IEVwUleed8itRoaFcHr1Wd8XJmsZWkG1v0pH6+kWWwAYmZY5WvLk6jvcpHnYpY2gRooQox1cBJgxptvwPjyNAPgVXDpnhMSMXcVvr8QsopqPmMTRI5K40a4dDT7K6glqJsQNY0xsr1VNHKizfvnJipYL7B/9UrjMRVD1Iy+cO1NszEPe34lCl8zB0J8KdXWhClTZYZlL/ZyawkjRGL1hUYAC9ZCi4YTqf+FjlvXm6Tba4GmVIDJs9cF1Swp+zr1ZC0injIW5/XvfWUMd8ZCSxBOcnnRp9DLOcxb/wjnkkPCE7OEJIsOYUr2Q6ctvAOHXkaa1olsSF1eOn5WFCkeG4M7xTBGJab1y8Aw0aFqJD22/bwdk6sX9Hjys0TEVngnhTz2bfY1ISdW2qqlpTftRdKSplJZegELGYZS9orklaX6i+BeeJsJNPx/FuqknvZQXaSKvEvwAthaEUYhzJPzhHRrwhnA/CZeEQ4a2GbQowlxyilPbaNJDdSSwsKSZh3M5LeidNPH35q+L6uJfTlhENzj6lRmF42tRLtxtzbjcpm+4VIBHDswH4bjfjL/CZ3QSBlUv5rabsG/VBLaBZm+U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
